from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm
from datetime import datetime
import io

app = FastAPI()

class CarDocumentRequest(BaseModel):
    buyer_name: str
    seller_name: str
    car_model: str
    car_year: int
    car_price: float
    
@app.post("/generate-car-document")
def generate_pdf(data: CarDocumentRequest):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 50, "CAR PURCHASE AGREEMENT")
    c.setLineWidth(1)
    c.setStrokeColor(colors.darkblue)
    c.line(50, height - 60, width - 50, height - 60)

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    c.drawString(50, height - 80, f"Agreement Number: {datetime.now().strftime('%Y%m%d%H%M%S')}")
    c.drawString(50, height - 95, f"Date: {datetime.now().strftime('%d.%m.%Y')}")

    # ---------- Buyer ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 130, "Buyer Information:")
    c.setFont("Helvetica", 12)
    c.rect(50, height - 195, width - 100, 60, stroke=1, fill=0)
    c.drawString(60, height - 150, f"Full Name: {data.buyer_name}")
    c.drawString(60, height - 165, "Address: _____________________________")
    c.drawString(60, height - 180, "Phone: ______________________________")

    # ---------- Seller ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 220, "Seller Information:")
    c.setFont("Helvetica", 12)
    c.rect(50, height - 285, width - 100, 60, stroke=1, fill=0)
    c.drawString(60, height - 240, f"Full Name / Company: {data.seller_name}")
    c.drawString(60, height - 255, "Address: _____________________________")
    c.drawString(60, height - 270, "Phone: ______________________________")

    # ---------- Car Details ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 310, "Vehicle Details:")
    c.setFont("Helvetica", 12)
    c.rect(50, height - 395, width - 100, 80, stroke=1, fill=0)
    c.drawString(60, height - 330, f"Make & Model: {data.car_model}")
    c.drawString(60, height - 350, f"Year: {data.car_year}")
    c.drawString(60, height - 370, f"Purchase Price: {data.car_price:.2f} EUR")
    c.drawString(60, height - 390, "VIN / Chassis Number: _____________________________")

    # ---------- Agreement Clauses ----------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 430, "Terms and Conditions:")
    c.setFont("Helvetica", 12)

    agreement_text = [
        "1. The Seller agrees to sell the above vehicle to the Buyer, and the Buyer agrees to purchase the vehicle at the price stated above.",
        "2. The Buyer has inspected the vehicle and accepts it in its current condition.",
        "3. All payments are made in accordance with the agreed price, and ownership is transferred upon full payment.",
        "4. Any disputes arising from this agreement shall be resolved according to the governing law.",
        "5. This document serves as a legally binding contract between the parties.",
    ]

    def wrap_text(text, max_width, canvas, x, y, line_height):
        words = text.split(" ")
        line = ""
        for word in words:
            test_line = f"{line} {word}".strip()
            if canvas.stringWidth(test_line, "Helvetica", 12) <= max_width:
                line = test_line
            else:
                canvas.drawString(x, y, line)
                line = word
                y -= line_height
        if line:
            canvas.drawString(x, y, line)
            y -= line_height
        return y

    y = height - 450
    max_width = width - 120 

    for line in agreement_text:
        y = wrap_text(line, max_width, c, 60, y, 18)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 120, "Buyer Signature:")
    c.line(100, 110, 300, 110)
    c.drawString(100, 95, "Date: ___________________")

    c.drawString(350, 120, "Seller Signature:")
    c.line(350, 110, 550, 110)
    c.drawString(350, 95, "Date: ___________________")

    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.gray)
    c.drawCentredString(width / 2, 30, "Generated by AutoMarket System | www.automarket.example")

    c.showPage()
    c.save()
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=car_purchase_agreement_{datetime.now().strftime('%Y%m%d')}.pdf"}
    )
